export type HosRuleSet = 
"AlaskaPassenger7Day" |
"AlaskaPassenger8Day" |
"AlaskaProperty7Day" |
"AlaskaProperty7DaySleeper" |
"AlaskaProperty8Day" |
"AlaskaProperty8DaySleeper" |
"America7Day" |
"America7DayBig" |
"America7DayBigSleeper" |
"America7DayNo34h" |
"America7DayNo34hSleeper" |
"America7DayPassenger" |
"America7DayRailroad" |
"America7DaySleeper" |
"America8Day" |
"America8DayBig" |
"America8DayBigSleeper" |
"America8DayNo34h" |
"America8DayNo34hSleeper" |
"America8DayPassenger" |
"America8DayRailroad" |
"America8DaySleeper" |
"AmericaNoRestRequirement7Day" |
"AmericaNoRestRequirement7DayBig" |
"AmericaNoRestRequirement7DayBigSleeper" |
"AmericaNoRestRequirement7DaySleeper" |
"AmericaNoRestRequirement8Day" |
"AmericaNoRestRequirement8DayBig" |
"AmericaNoRestRequirement8DayBigSleeper" |
"AmericaNoRestRequirement8DaySleeper" |
"AmericaNonCdlShortHaul7Day" |
"AmericaNonCdlShortHaul8Day" |
"AmericaSalesperson" |
"AmericaSalespersonNonCdlShortHaul" |
"AmericaShortHaul" |
"AmericaShortHaul14hrWorkday" |
"AmericaShortHaul8Day" |
"AmericaShortHaul8Day14hrWorkday" |
"AmericaShortHaul8DayNo34h" |
"AmericaShortHaulNo34h" |
"AmericaShortHaulPassenger" |
"AmericaShortHaulPassenger8Day" |
"AmericaTexas" |
"AmericaTexasShortHaul" |
"AmericaTexasShortHaul8Day" |
"AustraliaStandardHoursSoloExemptionHours" |
"BrazilShortHaul" |
"California8day" |
"CaliforniaFarmProduct" |
"CaliforniaFarmProductWithRestRequirement" |
"CaliforniaFlammableLiquid" |
"CaliforniaFlammableLiquidWithRestRequirement" |
"CaliforniaPassenger" |
"CaliforniaProperty" |
"CaliforniaPropertyShortHaul" |
"CaliforniaPropertyShortHaulWithRest" |
"CaliforniaSchoolPupil" |
"CaliforniaSchoolPupilWithRestRequirement" |
"CanadaBCLoggingTruck" |
"CanadaCycleOne" |
"CanadaCycleOneTeam" |
"CanadaCycleTwo" |
"CanadaCycleTwoTeam" |
"CanadaNorthOf60CycleOne" |
"CanadaNorthOf60CycleOneTeam" |
"CanadaNorthOf60CycleTwo" |
"CanadaNorthOf60CycleTwoTeam" |
"CanadaNorthOf60Oil" |
"CanadaNorthOf60OilTeam" |
"CanadaOil" |
"CanadaOilTeam" |
"CarrierExemption" |
"Florida7Day" |
"Florida8Day" |
"FloridaShortHaul7Day" |
"FloridaShortHaul8Day" |
"MalaysiaDrivingHours" |
"MarylandShortHaul7Day" |
"MarylandShortHaul8Day" |
"Nebraska7day" |
"Nebraska8day" |
"None" |
"None8Day" |
"NoneCanada" |
"NoneCanadaNorthOf60" |
"NorthDakota7Day" |
"NorthDakotaShortHaul7Day" |
"OilTransport7Day" |
"OilTransport7DayBig" |
"OilTransport7DayBigSleeper" |
"OilTransport7DaySleeper" |
"OilTransport8Day" |
"OilTransport8DayBig" |
"OilTransport8DayBigSleeper" |
"OilTransport8DaySleeper" |
"OilTransportCalifornia8day" |
"OilTransportCaliforniaProperty" |
"OilTransportNoRestRequirement7Day" |
"OilTransportNoRestRequirement7DayBig" |
"OilTransportNoRestRequirement7DayBigSleeper" |
"OilTransportNoRestRequirement7DaySleeper" |
"OilTransportNoRestRequirement8Day" |
"OilTransportNoRestRequirement8DayBig" |
"OilTransportNoRestRequirement8DayBigSleeper" |
"OilTransportNoRestRequirement8DaySleeper" |
"OilTransportShortHaul" |
"OilTransportShortHaul14hrWorkday" |
"OilTransportShortHaul8Day" |
"OilTransportShortHaul8Day14hrWorkday" |
"OilTransportTexas" |
"OilWell7Day" |
"OilWell7DayBig" |
"OilWell7DayBigSleeper" |
"OilWell7DaySleeper" |
"OilWell8Day" |
"OilWell8DayBig" |
"OilWell8DayBigSleeper" |
"OilWell8DaySleeper" |
"OilWellCalifornia8day" |
"OilWellCaliforniaProperty" |
"OilWellNoRestRequirement7Day" |
"OilWellNoRestRequirement7DayBig" |
"OilWellNoRestRequirement7DayBigSleeper" |
"OilWellNoRestRequirement7DaySleeper" |
"OilWellNoRestRequirement8Day" |
"OilWellNoRestRequirement8DayBig" |
"OilWellNoRestRequirement8DayBigSleeper" |
"OilWellNoRestRequirement8DaySleeper" |
"OilWellTexas" |
"Oregon7day" |
"Oregon8day" |
"SouthCarolina7Day" |
"SouthCarolina8Day" |
"WashingtonIntrastate7Day" |
"WashingtonIntrastate8Day";